version: '2'

run:
    timeout: 5m
    skip-dirs:
        - pkg/telegram

linters-settings:

linters:
    enable-all: true

issues:
    exclude-rules:
        - path: "pkg/telegram/.*\\.go"
          linters:
              - goanalysis_metalinter
          text: 'could not load export data: no export data for "github.com/zelenin/go-tdlib/client"'
