name: Linter

on: 
  push:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with: 
          go-version: 1.24.4

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
